### ISSUE TITLE
공통 컴포넌트 구현

### ISSUE THREAD

**Issue by Dobbymin** [kakao-tech-campus-2nd-step3/Team8_FE#5]
## 🧐 어떤 기능인가요?

> 추가하려는 기능에 대해 간결하게 설명해주세요.

공통 컴포넌트 구현 및 폰트 설정
## 🔧 작업 상세 내용
- [x] 웹앱 크기로 전체 크기 설정
- [x] 폰트 설정
- [x] 전역 color 설정

## 📆 예상 기간

> 예상 개발 기간을 대략적으로 작성해주세요.
> 
> 예) 0월 00일 ~ 0월 00일

9월 19일

**Comment by GitJIHO** [comment]
칭찬
